variables:
  GITHUB_USER: emotiq
  GITHUB_REPO: emotiq-external-libs

stages:
  - build
  - release
  - deploy

build:win:
  stage: build
  tags:
    - win
  script:
    - uname -a
    - env
    - ls -la
