variables:
  GITHUB_USER: emotiq
  GITHUB_REPO: emotiq-external-libs

stages:
  - build
  - test
  - release
  - deploy

.build: &build_definition
  stage: build
  script:
    - ./build-libs.bash
  artifacts:
    expire_in: 1 week
    paths:
      - var/

build:linux:
  <<: *build_definition
  tags:
    - linux

build:macos:
  <<: *build_definition
  tags:
    - macos

build:win32:
  <<: *build_definition
  tags:
    - win

.test: &test_definition
  stage: test
  tags:
    - linux
  script:
    - ls -alR var

test:linux:
  <<: *test_definition
  dependencies:
    - build:linux

test:macos:
  <<: *test_definition
  dependencies:
    - build:macos

test:win32:
  <<: *test_definition
  dependencies:
    - build:win32

release:
  stage: release
  tags:
    - linux
  only:
    - tags
  script:
    - github-release release --tag ${CI_COMMIT_TAG} -c ${CI_COMMIT_SHA} -d "${CI_COMMIT_MESSAGE}"

.deploy: &deploy_definition
  stage: deploy
  tags:
    - linux
  script:
    - ci/upload-file.sh $(cat var/local/artifact.txt)

deploy:linux:
  <<: *deploy_definition
  only:
    - tags
  dependencies:
    - build:linux

deploy:macos:
  <<: *deploy_definition
  only:
    - tags
  dependencies:
    - build:macos

deploy:win32:
  <<: *deploy_definition
  only:
    - tags
  dependencies:
    - build:win32
