variables:
  GITHUB_USER: emotiq
  GITHUB_REPO: emotiq-external-libs

stages:
  - build
  - release
  - deploy

.build_pbc: &build_definition_pbc
  stage: build
  script:
    - ./build-crypto-pairings.bash
  artifacts:
    expire_in: 1 week
    paths:
      - var/

.build_libuv: &build_definition_libuv
  stage: build
  script:
    - ./build-libuv.bash
  artifacts:
    expire_in: 1 week
    paths:
      - var/

build:linux:pbc:
  <<: *build_definition_pbc
  tags:
    - linux

build:macos:pbc:
  <<: *build_definition_pbc
  tags:
    - macos

build:linux:libuv:
  <<: *build_definition_libuv
  tags:
    - linux

build:macos:libuv:
  <<: *build_definition_libuv
  tags:
    - macos

release:
  stage: release
  tags:
    - linux
  only:
    - tags
  script:
    - github-release release --tag ${CI_COMMIT_TAG}

.deploy: &deploy_definition
  stage: deploy
  script:
    - ci/upload-file.sh $(cat var/local/artifact.txt)

deploy:linux:
  <<: *deploy_definition
  tags:
    - linux
  only:
    - tags
  dependencies:
    - build:linux:pbc

deploy:macos:
  <<: *deploy_definition
  tags:
    - linux
  only:
    - tags
  dependencies:
    - build:macos:pbc
