language: c

os:
  - linux
  - osx

compiler:
  - gcc

addons:
  apt:
    packages:
      - curl

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install curl    ; fi

script:
  - ./build-crypto-pairings.bash
