language: c

os:
  - linux
  - osx

compiler:
  - gcc

addons:
  apt:
    packages:
      - curl

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install curl    ; fi
script:
  - ./build-crypto-pairings.bash
  # - echo "Build and test goes here"

deploy:
  provider: releases
  api_key:
    secure: "JBClYRQCttTSlVQAuuUlMVMQUmc4Vyp+/jga8VwoFQuaCIY6V//T8wAcvQ92Tx07rIhPNs71FOPNKf7rWronhaGGPN8LHd6cXEuGtple0uBGyFlLgQTL3+xXLTx6goZ0sZXw/QDtKlTK/YlZ0aljXkvqpg2cTaHv99ShI6Gk2bsyLgTWvp0TU1OHbYRKFdvxQGZnDyl3BzQLLaGPX+GMGyM1mqUJL+5kFUnJk4vdc+yB+W/WCPCp/sd1C0kDmC2aUJAbqK4RkTBuATj1lKphWNsiq7IXWLXXB6IpyG9GoPP/2v2mlpKGzdBSRq/TLekJjBocf1nxsMgQ/5awz+GDaA+4eyTALEoSm9JjiXeP68uTDYENHdizodQixEnqIzLlxnfarz6p5kCkcabyTzbEbnSGJwEBxmOrRYUx7Kg1RilAJVqmI7VQEeIpi8OrEDAB2H/F7/UDShmoiE1UdxW3NzvwxYtMabnY4m3ZntJrqF9UIOCtj9HAQYFUS2NmkxDroEp4yCfXkUflIT0NB99JSSICdtDcNTtUnAJWTzu/JzWhTzHS24fqJVlv3wRpvat1hY42aJX70/qOK4Sx7P0+zVZKKDFmN7FvsrcFMurbsK5T3eEGv9N9H0eSPQ8iuhGgsrhqn3Fv5GsaadPMOCqobi5gGaqP1MBbe6N47/gZC2A="
  script:
    - ./build-crypto-pairings.bash
  file: "var/libLispPBCIntf-${TRAVIS_OS_NAME:-unknown}.tgz"
  skip_cleanup: true
  on:
    tags: true
    # all_branches: true
    # branches:
    #   only:
    #     - master

#
#
# jobs:
#   include:
#     - stage: GitHub Release
#       language: c
#       addons:
#         apt:
#           packages:
#             - curl
#       compiler:
#         - gcc
#       os:
#         - linux
#         - osx
#       deploy:
#         provider: releases
#         api_key:
#           secure: "JBClYRQCttTSlVQAuuUlMVMQUmc4Vyp+/jga8VwoFQuaCIY6V//T8wAcvQ92Tx07rIhPNs71FOPNKf7rWronhaGGPN8LHd6cXEuGtple0uBGyFlLgQTL3+xXLTx6goZ0sZXw/QDtKlTK/YlZ0aljXkvqpg2cTaHv99ShI6Gk2bsyLgTWvp0TU1OHbYRKFdvxQGZnDyl3BzQLLaGPX+GMGyM1mqUJL+5kFUnJk4vdc+yB+W/WCPCp/sd1C0kDmC2aUJAbqK4RkTBuATj1lKphWNsiq7IXWLXXB6IpyG9GoPP/2v2mlpKGzdBSRq/TLekJjBocf1nxsMgQ/5awz+GDaA+4eyTALEoSm9JjiXeP68uTDYENHdizodQixEnqIzLlxnfarz6p5kCkcabyTzbEbnSGJwEBxmOrRYUx7Kg1RilAJVqmI7VQEeIpi8OrEDAB2H/F7/UDShmoiE1UdxW3NzvwxYtMabnY4m3ZntJrqF9UIOCtj9HAQYFUS2NmkxDroEp4yCfXkUflIT0NB99JSSICdtDcNTtUnAJWTzu/JzWhTzHS24fqJVlv3wRpvat1hY42aJX70/qOK4Sx7P0+zVZKKDFmN7FvsrcFMurbsK5T3eEGv9N9H0eSPQ8iuhGgsrhqn3Fv5GsaadPMOCqobi5gGaqP1MBbe6N47/gZC2A="
#         file: "var/libLispPBCIntf-${TRAVIS_OS_NAME:-unknown}.tgz"
#         skip_cleanup: true
#         on:
#           branches:
#             only:
#               - master
#         # on:
#         #   tags: true
